default: &default
  description: Funny people on Twitter
  profiles:
    - StephenAtHome
    - johnlegend
    - realDonaldTrump
    - TheOnion
    - AnnaKendrick47
    - VP
development:
  <<: *default

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
